#!/bin/bash

set -euo pipefail

USER_HOME=$(getent passwd "$USER" | cut -d: -f6)
HYPR_CONFIG_DIR="$USER_HOME/.config/hypr"
HYPR_CONFIG_FILE="$HYPR_CONFIG_DIR/hyprland.conf"
DEFAULT_HYPR_CONFIG_DIR="/usr/share/binaryos/config/hypr"

if [ ! -f "$HYPR_CONFIG_FILE" ]; then
    mkdir -p "$HYPR_CONFIG_DIR"
    echo "source = $DEFAULT_HYPR_CONFIG_DIR/hyprland.conf" > "$HYPR_CONFIG_FILE"
fi
